-- ============================================================
-- GESTIONSTOCK2.0 — SOCLE GESTION FINANCIERE / COMPTABILITE V1
-- Branche : feature/comptabilite-v1
-- SQL Server 2017+
-- Idempotent : aucune table existante n'est modifiée.
-- ============================================================

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

USE GESTIONSTOCK;
GO

BEGIN TRANSACTION;
BEGIN TRY

-- ============================================================
-- 1. SITES
-- ============================================================
IF OBJECT_ID('FSITE', 'U') IS NULL
BEGIN
    CREATE TABLE FSITE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(30) NOT NULL,
        NOM             NVARCHAR(200) NOT NULL,
        DESCRIPTION     NVARCHAR(500) NULL,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        DELETION_BY     INT NULL,
        DELETION_AT     DATETIME NULL,

        CONSTRAINT PK_FSITE PRIMARY KEY (ID),
        CONSTRAINT UQ_FSITE_CODE UNIQUE (CODE),
        CONSTRAINT FK_FSITE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FSITE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FSITE_DELETION_BY FOREIGN KEY (DELETION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 2. MONNAIES
-- ============================================================
IF OBJECT_ID('FMONNAIE', 'U') IS NULL
BEGIN
    CREATE TABLE FMONNAIE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(10) NOT NULL,
        NOM             NVARCHAR(100) NOT NULL,
        SYMBOLE         NVARCHAR(10) NULL,
        DECIMALES       TINYINT NOT NULL DEFAULT 2,
        TAUX_REFERENCE  DECIMAL(18,8) NULL,
        EST_REFERENCE   BIT NOT NULL DEFAULT 0,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        DELETION_BY     INT NULL,
        DELETION_AT     DATETIME NULL,

        CONSTRAINT PK_FMONNAIE PRIMARY KEY (ID),
        CONSTRAINT UQ_FMONNAIE_CODE UNIQUE (CODE),
        CONSTRAINT CK_FMONNAIE_DECIMALES CHECK (DECIMALES BETWEEN 0 AND 6),
        CONSTRAINT FK_FMONNAIE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FMONNAIE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FMONNAIE_DELETION_BY FOREIGN KEY (DELETION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 3. EXERCICES
-- ============================================================
IF OBJECT_ID('FEXERCICE', 'U') IS NULL
BEGIN
    CREATE TABLE FEXERCICE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(20) NOT NULL,
        LIBELLE         NVARCHAR(100) NOT NULL,
        DATE_DEBUT      DATE NOT NULL,
        DATE_FIN        DATE NOT NULL,
        STATUT          VARCHAR(20) NOT NULL DEFAULT 'OUVERT',
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        CLOTURE_BY      INT NULL,
        CLOTURE_AT      DATETIME NULL,

        CONSTRAINT PK_FEXERCICE PRIMARY KEY (ID),
        CONSTRAINT UQ_FEXERCICE_CODE UNIQUE (CODE),
        CONSTRAINT CK_FEXERCICE_DATES CHECK (DATE_FIN >= DATE_DEBUT),
        CONSTRAINT CK_FEXERCICE_STATUT CHECK (STATUT IN ('OUVERT','CLOTURE','ARCHIVE')),
        CONSTRAINT FK_FEXERCICE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FEXERCICE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FEXERCICE_CLOTURE_BY FOREIGN KEY (CLOTURE_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 4. PERIODES COMPTABLES
-- ============================================================
IF OBJECT_ID('FPERIODE', 'U') IS NULL
BEGIN
    CREATE TABLE FPERIODE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        EXERCICE_ID     UNIQUEIDENTIFIER NOT NULL,
        NUMERO          TINYINT NOT NULL,
        LIBELLE         NVARCHAR(100) NOT NULL,
        DATE_DEBUT      DATE NOT NULL,
        DATE_FIN        DATE NOT NULL,
        STATUT          VARCHAR(20) NOT NULL DEFAULT 'OUVERTE',

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        CLOTURE_BY      INT NULL,
        CLOTURE_AT      DATETIME NULL,

        CONSTRAINT PK_FPERIODE PRIMARY KEY (ID),
        CONSTRAINT UQ_FPERIODE_EXERCICE_NUMERO UNIQUE (EXERCICE_ID, NUMERO),
        CONSTRAINT CK_FPERIODE_NUMERO CHECK (NUMERO BETWEEN 1 AND 99),
        CONSTRAINT CK_FPERIODE_DATES CHECK (DATE_FIN >= DATE_DEBUT),
        CONSTRAINT CK_FPERIODE_STATUT CHECK (STATUT IN ('OUVERTE','CLOTUREE')),
        CONSTRAINT FK_FPERIODE_EXERCICE FOREIGN KEY (EXERCICE_ID) REFERENCES FEXERCICE(ID),
        CONSTRAINT FK_FPERIODE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FPERIODE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FPERIODE_CLOTURE_BY FOREIGN KEY (CLOTURE_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 5. PLANS / AXES DE REFERENCE
-- Un même moteur gère les plans demandés et les axes futurs.
-- ============================================================
IF OBJECT_ID('FPLAN', 'U') IS NULL
BEGIN
    CREATE TABLE FPLAN
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(30) NOT NULL,
        NOM             NVARCHAR(200) NOT NULL,
        TYPE_PLAN       VARCHAR(40) NOT NULL,
        DESCRIPTION     NVARCHAR(500) NULL,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        DELETION_BY     INT NULL,
        DELETION_AT     DATETIME NULL,

        CONSTRAINT PK_FPLAN PRIMARY KEY (ID),
        CONSTRAINT UQ_FPLAN_CODE UNIQUE (CODE),
        CONSTRAINT CK_FPLAN_TYPE CHECK
        (
            TYPE_PLAN IN
            (
                'COMPTABLE',
                'OPERATIONS_PUBLIQUES',
                'ACTIVITES',
                'GEOGRAPHIQUE',
                'FINANCIER',
                'CATEGORIES_FINANCIERES',
                'TIERS',
                'AXE'
            )
        ),
        CONSTRAINT FK_FPLAN_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FPLAN_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FPLAN_DELETION_BY FOREIGN KEY (DELETION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

IF OBJECT_ID('FPLAN_ELEMENT', 'U') IS NULL
BEGIN
    CREATE TABLE FPLAN_ELEMENT
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        PLAN_ID         UNIQUEIDENTIFIER NOT NULL,
        CODE            VARCHAR(50) NOT NULL,
        LIBELLE         NVARCHAR(250) NOT NULL,
        PARENT_ID       UNIQUEIDENTIFIER NULL,
        NIVEAU          INT NOT NULL DEFAULT 1,
        TYPE_ELEMENT    VARCHAR(20) NOT NULL DEFAULT 'DETAIL',
        NATURE          VARCHAR(30) NULL,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        DELETION_BY     INT NULL,
        DELETION_AT     DATETIME NULL,

        CONSTRAINT PK_FPLAN_ELEMENT PRIMARY KEY (ID),
        CONSTRAINT UQ_FPLAN_ELEMENT_CODE UNIQUE (PLAN_ID, CODE),
        CONSTRAINT CK_FPLAN_ELEMENT_TYPE CHECK (TYPE_ELEMENT IN ('RUBRIQUE','DETAIL')),
        CONSTRAINT FK_FPLAN_ELEMENT_PLAN FOREIGN KEY (PLAN_ID) REFERENCES FPLAN(ID),
        CONSTRAINT FK_FPLAN_ELEMENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FPLAN_ELEMENT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FPLAN_ELEMENT_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FPLAN_ELEMENT_DELETION_BY FOREIGN KEY (DELETION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 6. TIERS
-- ============================================================
IF OBJECT_ID('FTIERS', 'U') IS NULL
BEGIN
    CREATE TABLE FTIERS
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(50) NOT NULL,
        NOM             NVARCHAR(250) NOT NULL,
        TYPE_TIERS      VARCHAR(30) NOT NULL DEFAULT 'AUTRE',
        PLAN_ELEMENT_ID  UNIQUEIDENTIFIER NULL,
        EMAIL           NVARCHAR(150) NULL,
        TELEPHONE       NVARCHAR(50) NULL,
        ADRESSE         NVARCHAR(500) NULL,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        DELETION_BY     INT NULL,
        DELETION_AT     DATETIME NULL,

        CONSTRAINT PK_FTIERS PRIMARY KEY (ID),
        CONSTRAINT UQ_FTIERS_CODE UNIQUE (CODE),
        CONSTRAINT CK_FTIERS_TYPE CHECK (TYPE_TIERS IN ('FOURNISSEUR','CLIENT','AGENT','PARTENAIRE','AUTRE')),
        CONSTRAINT FK_FTIERS_PLAN_ELEMENT FOREIGN KEY (PLAN_ELEMENT_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FTIERS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FTIERS_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FTIERS_DELETION_BY FOREIGN KEY (DELETION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 7. JOURNAUX
-- ============================================================
IF OBJECT_ID('FJOURNAL', 'U') IS NULL
BEGIN
    CREATE TABLE FJOURNAL
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(20) NOT NULL,
        LIBELLE         NVARCHAR(150) NOT NULL,
        TYPE_JOURNAL    VARCHAR(30) NOT NULL,
        SITE_ID         UNIQUEIDENTIFIER NULL,
        MONNAIE_ID      UNIQUEIDENTIFIER NULL,
        COMPTE_BANQUE_ID UNIQUEIDENTIFIER NULL,
        PREFIXE_NUMERO  VARCHAR(20) NULL,
        DERNIER_NUMERO  INT NOT NULL DEFAULT 0,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        DELETION_BY     INT NULL,
        DELETION_AT     DATETIME NULL,

        CONSTRAINT PK_FJOURNAL PRIMARY KEY (ID),
        CONSTRAINT UQ_FJOURNAL_CODE UNIQUE (CODE),
        CONSTRAINT CK_FJOURNAL_TYPE CHECK (TYPE_JOURNAL IN ('ACHATS','VENTES','BANQUE','CAISSE','OPERATIONS_DIVERSES','GENERAL')),
        CONSTRAINT FK_FJOURNAL_SITE FOREIGN KEY (SITE_ID) REFERENCES FSITE(ID),
        CONSTRAINT FK_FJOURNAL_MONNAIE FOREIGN KEY (MONNAIE_ID) REFERENCES FMONNAIE(ID),
        CONSTRAINT FK_FJOURNAL_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FJOURNAL_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FJOURNAL_DELETION_BY FOREIGN KEY (DELETION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 8. ECRITURES COMPTABLES — ENTETE
-- ============================================================
IF OBJECT_ID('FECRITURE', 'U') IS NULL
BEGIN
    CREATE TABLE FECRITURE
    (
        ID                  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        EXERCICE_ID         UNIQUEIDENTIFIER NOT NULL,
        PERIODE_ID          UNIQUEIDENTIFIER NOT NULL,
        JOURNAL_ID          UNIQUEIDENTIFIER NOT NULL,
        SITE_ID             UNIQUEIDENTIFIER NULL,
        MONNAIE_ID          UNIQUEIDENTIFIER NOT NULL,

        NUMERO              VARCHAR(50) NOT NULL,
        DATE_COMPTABLE      DATE NOT NULL,
        DATE_PIECE          DATE NULL,
        REFERENCE           VARCHAR(100) NULL,
        LIBELLE             NVARCHAR(500) NOT NULL,

        TOTAL_DEBIT         DECIMAL(19,4) NOT NULL DEFAULT 0,
        TOTAL_CREDIT        DECIMAL(19,4) NOT NULL DEFAULT 0,

        STATUT              VARCHAR(25) NOT NULL DEFAULT 'BROUILLON',
        ECRITURE_ORIGINE_ID UNIQUEIDENTIFIER NULL,
        CORRECTION_MOTIF    NVARCHAR(1000) NULL,

        CREATED_BY          INT NULL,
        CREATED_AT          DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY          INT NULL,
        UPDATED_AT          DATETIME NULL,
        VALIDATED_BY        INT NULL,
        VALIDATED_AT        DATETIME NULL,
        CORRECTED_BY        INT NULL,
        CORRECTED_AT        DATETIME NULL,
        CORRECTION_BY       INT NULL,
        CORRECTION_AT       DATETIME NULL,

        CONSTRAINT PK_FECRITURE PRIMARY KEY (ID),
        CONSTRAINT UQ_FECRITURE_JOURNAL_NUMERO UNIQUE (JOURNAL_ID, EXERCICE_ID, NUMERO),
        CONSTRAINT CK_FECRITURE_STATUT CHECK
        (
            STATUT IN ('BROUILLON','A_VALIDER','VALIDEE','COMPTABILISEE','CORRIGEE','ANNULEE')
        ),
        CONSTRAINT FK_FECRITURE_EXERCICE FOREIGN KEY (EXERCICE_ID) REFERENCES FEXERCICE(ID),
        CONSTRAINT FK_FECRITURE_PERIODE FOREIGN KEY (PERIODE_ID) REFERENCES FPERIODE(ID),
        CONSTRAINT FK_FECRITURE_JOURNAL FOREIGN KEY (JOURNAL_ID) REFERENCES FJOURNAL(ID),
        CONSTRAINT FK_FECRITURE_SITE FOREIGN KEY (SITE_ID) REFERENCES FSITE(ID),
        CONSTRAINT FK_FECRITURE_MONNAIE FOREIGN KEY (MONNAIE_ID) REFERENCES FMONNAIE(ID),
        CONSTRAINT FK_FECRITURE_ORIGINE FOREIGN KEY (ECRITURE_ORIGINE_ID) REFERENCES FECRITURE(ID),
        CONSTRAINT FK_FECRITURE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FECRITURE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FECRITURE_VALIDATED_BY FOREIGN KEY (VALIDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FECRITURE_CORRECTED_BY FOREIGN KEY (CORRECTED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FECRITURE_CORRECTION_BY FOREIGN KEY (CORRECTION_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 9. LIGNES D'ECRITURES
-- ============================================================
IF OBJECT_ID('FECRITURE_LIGNE', 'U') IS NULL
BEGIN
    CREATE TABLE FECRITURE_LIGNE
    (
        ID                  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        ECRITURE_ID         UNIQUEIDENTIFIER NOT NULL,
        ORDRE               INT NOT NULL,

        COMPTE_ID           UNIQUEIDENTIFIER NOT NULL,
        TIERS_ID            UNIQUEIDENTIFIER NULL,
        LIBELLE             NVARCHAR(500) NULL,

        DEBIT               DECIMAL(19,4) NOT NULL DEFAULT 0,
        CREDIT              DECIMAL(19,4) NOT NULL DEFAULT 0,

        OPERATION_PUBLIQUE_ID UNIQUEIDENTIFIER NULL,
        ACTIVITE_ID         UNIQUEIDENTIFIER NULL,
        GEOGRAPHIE_ID       UNIQUEIDENTIFIER NULL,
        FINANCIER_ID        UNIQUEIDENTIFIER NULL,
        CATEGORIE_FINANCIERE_ID UNIQUEIDENTIFIER NULL,

        AXE1_ID             UNIQUEIDENTIFIER NULL,
        AXE2_ID             UNIQUEIDENTIFIER NULL,
        AXE3_ID             UNIQUEIDENTIFIER NULL,

        LETTRABLE           BIT NOT NULL DEFAULT 0,

        CREATED_BY          INT NULL,
        CREATED_AT          DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY          INT NULL,
        UPDATED_AT          DATETIME NULL,

        CONSTRAINT PK_FECRITURE_LIGNE PRIMARY KEY (ID),
        CONSTRAINT UQ_FECRITURE_LIGNE_ORDRE UNIQUE (ECRITURE_ID, ORDRE),
        CONSTRAINT CK_FECRITURE_LIGNE_MONTANT CHECK
        (
            (DEBIT >= 0 AND CREDIT >= 0)
            AND NOT (DEBIT > 0 AND CREDIT > 0)
            AND (DEBIT > 0 OR CREDIT > 0)
        ),
        CONSTRAINT FK_FECRITURE_LIGNE_ECRITURE FOREIGN KEY (ECRITURE_ID) REFERENCES FECRITURE(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_COMPTE FOREIGN KEY (COMPTE_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_TIERS FOREIGN KEY (TIERS_ID) REFERENCES FTIERS(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_OP FOREIGN KEY (OPERATION_PUBLIQUE_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_ACTIVITE FOREIGN KEY (ACTIVITE_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_GEO FOREIGN KEY (GEOGRAPHIE_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_FINANCIER FOREIGN KEY (FINANCIER_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_CATFIN FOREIGN KEY (CATEGORIE_FINANCIERE_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_AXE1 FOREIGN KEY (AXE1_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_AXE2 FOREIGN KEY (AXE2_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_AXE3 FOREIGN KEY (AXE3_ID) REFERENCES FPLAN_ELEMENT(ID),
        CONSTRAINT FK_FECRITURE_LIGNE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FECRITURE_LIGNE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 10. LETTRAGE
-- ============================================================
IF OBJECT_ID('FLETTRAGE', 'U') IS NULL
BEGIN
    CREATE TABLE FLETTRAGE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        CODE            VARCHAR(30) NOT NULL,
        DATE_LETTRAGE   DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE),
        MONTANT         DECIMAL(19,4) NOT NULL DEFAULT 0,
        ACTIVE          BIT NOT NULL DEFAULT 1,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        DELETED_BY      INT NULL,
        DELETED_AT      DATETIME NULL,

        CONSTRAINT PK_FLETTRAGE PRIMARY KEY (ID),
        CONSTRAINT UQ_FLETTRAGE_CODE UNIQUE (CODE),
        CONSTRAINT FK_FLETTRAGE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FLETTRAGE_DELETED_BY FOREIGN KEY (DELETED_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

IF OBJECT_ID('FLETTRAGE_LIGNE', 'U') IS NULL
BEGIN
    CREATE TABLE FLETTRAGE_LIGNE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        LETTRAGE_ID     UNIQUEIDENTIFIER NOT NULL,
        ECRITURE_LIGNE_ID UNIQUEIDENTIFIER NOT NULL,
        MONTANT_LETTRE  DECIMAL(19,4) NOT NULL,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),

        CONSTRAINT PK_FLETTRAGE_LIGNE PRIMARY KEY (ID),
        CONSTRAINT UQ_FLETTRAGE_LIGNE UNIQUE (LETTRAGE_ID, ECRITURE_LIGNE_ID),
        CONSTRAINT CK_FLETTRAGE_LIGNE_MONTANT CHECK (MONTANT_LETTRE > 0),
        CONSTRAINT FK_FLETTRAGE_LIGNE_LETTRAGE FOREIGN KEY (LETTRAGE_ID) REFERENCES FLETTRAGE(ID),
        CONSTRAINT FK_FLETTRAGE_LIGNE_ECRITURE FOREIGN KEY (ECRITURE_LIGNE_ID) REFERENCES FECRITURE_LIGNE(ID),
        CONSTRAINT FK_FLETTRAGE_LIGNE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 11. RELEVES BANCAIRES
-- ============================================================
IF OBJECT_ID('FRELEVE_BANCAIRE', 'U') IS NULL
BEGIN
    CREATE TABLE FRELEVE_BANCAIRE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        JOURNAL_ID      UNIQUEIDENTIFIER NOT NULL,
        NUMERO_RELEVE  VARCHAR(50) NOT NULL,
        DATE_DEBUT      DATE NOT NULL,
        DATE_FIN        DATE NOT NULL,
        SOLDE_INITIAL   DECIMAL(19,4) NULL,
        SOLDE_FINAL     DECIMAL(19,4) NULL,
        STATUT          VARCHAR(20) NOT NULL DEFAULT 'OUVERT',
        FICHIER_SOURCE  NVARCHAR(255) NULL,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        UPDATED_BY      INT NULL,
        UPDATED_AT      DATETIME NULL,
        CLOTURE_BY      INT NULL,
        CLOTURE_AT      DATETIME NULL,

        CONSTRAINT PK_FRELEVE_BANCAIRE PRIMARY KEY (ID),
        CONSTRAINT UQ_FRELEVE_BANCAIRE_NUMERO UNIQUE (JOURNAL_ID, NUMERO_RELEVE),
        CONSTRAINT CK_FRELEVE_BANCAIRE_DATES CHECK (DATE_FIN >= DATE_DEBUT),
        CONSTRAINT CK_FRELEVE_BANCAIRE_STATUT CHECK (STATUT IN ('OUVERT','RAPPROCHE','CLOTURE')),
        CONSTRAINT FK_FRELEVE_BANCAIRE_JOURNAL FOREIGN KEY (JOURNAL_ID) REFERENCES FJOURNAL(ID),
        CONSTRAINT FK_FRELEVE_BANCAIRE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FRELEVE_BANCAIRE_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FRELEVE_BANCAIRE_CLOTURE_BY FOREIGN KEY (CLOTURE_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

IF OBJECT_ID('FRELEVE_LIGNE', 'U') IS NULL
BEGIN
    CREATE TABLE FRELEVE_LIGNE
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        RELEVE_ID       UNIQUEIDENTIFIER NOT NULL,
        ORDRE           INT NOT NULL,
        DATE_OPERATION  DATE NOT NULL,
        REFERENCE       VARCHAR(100) NULL,
        LIBELLE         NVARCHAR(500) NULL,
        DEBIT           DECIMAL(19,4) NOT NULL DEFAULT 0,
        CREDIT          DECIMAL(19,4) NOT NULL DEFAULT 0,
        SOLDE           DECIMAL(19,4) NULL,
        RAPPROCHE       BIT NOT NULL DEFAULT 0,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),

        CONSTRAINT PK_FRELEVE_LIGNE PRIMARY KEY (ID),
        CONSTRAINT UQ_FRELEVE_LIGNE_ORDRE UNIQUE (RELEVE_ID, ORDRE),
        CONSTRAINT CK_FRELEVE_LIGNE_MONTANT CHECK
        (
            DEBIT >= 0 AND CREDIT >= 0
            AND NOT (DEBIT > 0 AND CREDIT > 0)
        ),
        CONSTRAINT FK_FRELEVE_LIGNE_RELEVE FOREIGN KEY (RELEVE_ID) REFERENCES FRELEVE_BANCAIRE(ID),
        CONSTRAINT FK_FRELEVE_LIGNE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 12. RAPPROCHEMENT BANCAIRE
-- ============================================================
IF OBJECT_ID('FRECONCILIATION', 'U') IS NULL
BEGIN
    CREATE TABLE FRECONCILIATION
    (
        ID              UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        RELEVE_ID       UNIQUEIDENTIFIER NOT NULL,
        DATE_RAPPROCHEMENT DATE NOT NULL DEFAULT CAST(GETDATE() AS DATE),
        MONTANT_BANQUE  DECIMAL(19,4) NOT NULL DEFAULT 0,
        MONTANT_COMPTA  DECIMAL(19,4) NOT NULL DEFAULT 0,
        ECART           DECIMAL(19,4) NOT NULL DEFAULT 0,
        STATUT          VARCHAR(20) NOT NULL DEFAULT 'EN_COURS',
        OBSERVATIONS    NVARCHAR(1000) NULL,

        CREATED_BY      INT NULL,
        CREATED_AT      DATETIME NOT NULL DEFAULT GETDATE(),
        VALIDATED_BY    INT NULL,
        VALIDATED_AT    DATETIME NULL,

        CONSTRAINT PK_FRECONCILIATION PRIMARY KEY (ID),
        CONSTRAINT CK_FRECONCILIATION_STATUT CHECK (STATUT IN ('EN_COURS','RAPPROCHE','ECART')),
        CONSTRAINT FK_FRECONCILIATION_RELEVE FOREIGN KEY (RELEVE_ID) REFERENCES FRELEVE_BANCAIRE(ID),
        CONSTRAINT FK_FRECONCILIATION_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER),
        CONSTRAINT FK_FRECONCILIATION_VALIDATED_BY FOREIGN KEY (VALIDATED_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

IF OBJECT_ID('FRECONCILIATION_LIGNE', 'U') IS NULL
BEGIN
    CREATE TABLE FRECONCILIATION_LIGNE
    (
        ID                  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
        RECONCILIATION_ID   UNIQUEIDENTIFIER NOT NULL,
        RELEVE_LIGNE_ID     UNIQUEIDENTIFIER NOT NULL,
        ECRITURE_LIGNE_ID   UNIQUEIDENTIFIER NOT NULL,
        MONTANT_BANQUE      DECIMAL(19,4) NOT NULL,
        MONTANT_COMPTA      DECIMAL(19,4) NOT NULL,
        ECART               DECIMAL(19,4) NOT NULL DEFAULT 0,
        TYPE_ECART          VARCHAR(30) NULL,
        OBSERVATION         NVARCHAR(500) NULL,

        CREATED_BY          INT NULL,
        CREATED_AT          DATETIME NOT NULL DEFAULT GETDATE(),

        CONSTRAINT PK_FRECONCILIATION_LIGNE PRIMARY KEY (ID),
        CONSTRAINT UQ_FRECONCILIATION_LIGNE UNIQUE (RECONCILIATION_ID, RELEVE_LIGNE_ID, ECRITURE_LIGNE_ID),
        CONSTRAINT FK_FRECONCILIATION_LIGNE_RECONCILIATION FOREIGN KEY (RECONCILIATION_ID) REFERENCES FRECONCILIATION(ID),
        CONSTRAINT FK_FRECONCILIATION_LIGNE_RELEVE FOREIGN KEY (RELEVE_LIGNE_ID) REFERENCES FRELEVE_LIGNE(ID),
        CONSTRAINT FK_FRECONCILIATION_LIGNE_ECRITURE FOREIGN KEY (ECRITURE_LIGNE_ID) REFERENCES FECRITURE_LIGNE(ID),
        CONSTRAINT FK_FRECONCILIATION_LIGNE_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS(IDUSER)
    );
END;
GO

-- ============================================================
-- 13. INDEX
-- ============================================================
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FPLAN_ELEMENT_PLAN' AND object_id=OBJECT_ID('FPLAN_ELEMENT'))
    CREATE INDEX IX_FPLAN_ELEMENT_PLAN ON FPLAN_ELEMENT(PLAN_ID, ACTIVE, CODE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FTIERS_PLAN_ELEMENT' AND object_id=OBJECT_ID('FTIERS'))
    CREATE INDEX IX_FTIERS_PLAN_ELEMENT ON FTIERS(PLAN_ELEMENT_ID, ACTIVE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FECRITURE_DATE' AND object_id=OBJECT_ID('FECRITURE'))
    CREATE INDEX IX_FECRITURE_DATE ON FECRITURE(DATE_COMPTABLE, JOURNAL_ID, STATUT);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FECRITURE_EXERCICE_PERIODE' AND object_id=OBJECT_ID('FECRITURE'))
    CREATE INDEX IX_FECRITURE_EXERCICE_PERIODE ON FECRITURE(EXERCICE_ID, PERIODE_ID, DATE_COMPTABLE);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FECRITURE_LIGNE_COMPTE' AND object_id=OBJECT_ID('FECRITURE_LIGNE'))
    CREATE INDEX IX_FECRITURE_LIGNE_COMPTE ON FECRITURE_LIGNE(COMPTE_ID, ECRITURE_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FECRITURE_LIGNE_TIERS' AND object_id=OBJECT_ID('FECRITURE_LIGNE'))
    CREATE INDEX IX_FECRITURE_LIGNE_TIERS ON FECRITURE_LIGNE(TIERS_ID, ECRITURE_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FLETTRAGE_LIGNE_ECRITURE' AND object_id=OBJECT_ID('FLETTRAGE_LIGNE'))
    CREATE INDEX IX_FLETTRAGE_LIGNE_ECRITURE ON FLETTRAGE_LIGNE(ECRITURE_LIGNE_ID);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FRELEVE_LIGNE_DATE' AND object_id=OBJECT_ID('FRELEVE_LIGNE'))
    CREATE INDEX IX_FRELEVE_LIGNE_DATE ON FRELEVE_LIGNE(RELEVE_ID, DATE_OPERATION);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_FRECONCILIATION_LIGNE_ECRITURE' AND object_id=OBJECT_ID('FRECONCILIATION_LIGNE'))
    CREATE INDEX IX_FRECONCILIATION_LIGNE_ECRITURE ON FRECONCILIATION_LIGNE(ECRITURE_LIGNE_ID);

COMMIT TRANSACTION;
PRINT 'GESTION FINANCIERE V1 : structure créée avec succès.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
