-- =====================================================
-- GESTION SCOLAIRE - BASE DE DONNÉES COMPLÈTE (CORRIGÉE)
-- =====================================================

IF NOT EXISTS (SELECT *
FROM sys.databases
WHERE name = 'GESTIONSTOCK')
BEGIN
    CREATE DATABASE GESTIONSTOCK;
END
GO

USE GESTIONSTOCK;
GO

-- =====================================================
-- TABLE USERROLE
-- =====================================================
IF NOT EXISTS (SELECT *
FROM sys.tables
WHERE name = 'USERROLE')
BEGIN
    CREATE TABLE USERROLE
    (
        ROLEID INT PRIMARY KEY,
        ROLENAME VARCHAR(50) NOT NULL UNIQUE
    );
END
GO

-- =====================================================
-- TABLE USERS
-- =====================================================
IF NOT EXISTS (SELECT *
FROM sys.tables
WHERE name = 'USERS')
BEGIN
    CREATE TABLE USERS
    (
        IDUSER INT IDENTITY(1,1) PRIMARY KEY,
        USERNAME NVARCHAR(100) NOT NULL UNIQUE,
        NOM NVARCHAR(100) NOT NULL,
        EMAIL NVARCHAR(100) UNIQUE NOT NULL,
        PWD NVARCHAR(255) NOT NULL,
        ROLEID INT NOT NULL,
        TELEPHONE NVARCHAR(20),
        ACTIVE BIT NOT NULL DEFAULT 1,
        CREATED_AT DATETIME DEFAULT GETDATE(),
        CREATED_BY INT NULL,
        UPDATED_AT DATETIME NULL,
        UPDATED_BY INT NULL,
        DELETION_AT DATETIME NULL,
        DELETION_BY INT NULL,
        SESSION_TOKEN NVARCHAR(100),
        LAST_LOGIN DATETIME,
        LAST_PC NVARCHAR(100),
        MENU_PERMISSIONS NVARCHAR(MAX) NULL,
        BLOCKED_UNTIL DATETIME NULL,

        CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLEID) REFERENCES USERROLE(ROLEID)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM USERROLE)
BEGIN
    INSERT INTO USERROLE
        (ROLEID, ROLENAME)
    VALUES
        (0, 'SuperAdmin'),
        (1, 'Admin'),
        (2, 'User'),
        (3, 'Logisticien'),
        (4, 'Comptable');
END

IF NOT EXISTS (SELECT 1 FROM USERS)
BEGIN
    INSERT INTO USERS
        (USERNAME, NOM, EMAIL, PWD, ROLEID, TELEPHONE, ACTIVE)
    VALUES
        (N'SuperAdmin', N'SuperAdmin', N'admin@ecole.com', N'0', 0, N'0321234500', 1);
END
GO

-- ============================================================
-- EXTENSION STOCK
-- ============================================================

-- 1. UNITES DE MESURE
CREATE TABLE SUNITE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CODE VARCHAR(20) NOT NULL,
    NOM VARCHAR(100) NOT NULL,
    ACTIVE BIT DEFAULT 1,
    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 2. CATEGORIES D'ARTICLES
CREATE TABLE SCATEGORIE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CODE VARCHAR(50) NOT NULL,
    NOM VARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(500),
    PARENT_ID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES SCATEGORIE(ID),
    ACTIVE BIT DEFAULT 1,
    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 3. FOURNISSEURS
CREATE TABLE SFOURNISSEUR (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CODE VARCHAR(50) NOT NULL,
    NOM VARCHAR(200) NOT NULL,
    ADRESSE NVARCHAR(500),
    TELEPHONE VARCHAR(50),
    EMAIL VARCHAR(100),
    CONTACT_NOM VARCHAR(100),
    CONTACT_TELEPHONE VARCHAR(50),
    SIRET VARCHAR(20),
    ACTIVE BIT DEFAULT 1,
    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 4. EMPLACEMENTS DE STOCKAGE
CREATE TABLE SEMPLACEMENT (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CODE VARCHAR(50) NOT NULL,
    NOM VARCHAR(200) NOT NULL,
    TYPE VARCHAR(20),
    PARENT_ID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES SEMPLACEMENT(ID),
    ACTIVE BIT DEFAULT 1,
    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 5. ARTICLES (CŒUR DU STOCK)
CREATE TABLE MARTICLE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    CODE VARCHAR(50) NOT NULL,
    CODE_BARRE VARCHAR(50) NULL,
    NOM VARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(500),

    -- Relations (toutes les FK vers des tables avec ID en UNIQUEIDENTIFIER)
    CATEGORIE_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SCATEGORIE(ID),
    UNITE_MESURE_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SUNITE(ID),
    FOURNISSEUR_PREFERE_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SFOURNISSEUR(ID),
    EMPLACEMENT_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SEMPLACEMENT(ID),

    -- Caractéristiques
    SEUIL_MIN DECIMAL(18,2) DEFAULT 0,
    SEUIL_MAX DECIMAL(18,2) DEFAULT 0,
    SEUIL_ALERTE DECIMAL(18,2) DEFAULT 0,
    POIDS DECIMAL(10,2) NULL,
    VOLUME DECIMAL(10,2) NULL,

    -- Gestion
    ACTIVE BIT DEFAULT 1,
    EST_SERVICE BIT DEFAULT 0,
    EST_PERISSABLE BIT DEFAULT 0,
    DATE_PEREMPTION DATE NULL,

    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 6. STOCK (quantités par emplacement)
CREATE TABLE SSTOCK (
    ID INT PRIMARY KEY IDENTITY(1,1),
    ARTICLE_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES MARTICLE(ID),
    EMPLACEMENT_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SEMPLACEMENT(ID),
    STATUT VARCHAR(20) DEFAULT 'NORMALE' CHECK (STATUT IN ('NORMALE', 'ALERTE', 'RUPTURE')),
    QUANTITE_MVT DECIMAL(18,2) NOT NULL DEFAULT 0,
    QUANTITE_ACTUELLE DECIMAL(18,2) NOT NULL DEFAULT 0,
    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL,

    CONSTRAINT UQ_STOCK_ARTICLE_EMPLACEMENT UNIQUE(ARTICLE_ID, EMPLACEMENT_ID)
);

-- 7. MOUVEMENTS DE STOCK (historique)
CREATE TABLE MSTOCK (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    ARTICLE_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES MARTICLE(ID),
    EMPLACEMENT_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SEMPLACEMENT(ID),

    TYPE VARCHAR(20) NOT NULL,
    QUANTITE DECIMAL(18,2) NOT NULL,
    QUANTITE_AVANT DECIMAL(18,2) NOT NULL,
    QUANTITE_APRES DECIMAL(18,2) NOT NULL,

    -- Références
    REFERENCE_TYPE VARCHAR(50),
    REFERENCE_ID INT,
    REFERENCE_NUMERO VARCHAR(50),

    -- Métadonnées
    MOTIF NVARCHAR(500),
    PRIX_UNITAIRE DECIMAL(18,2) NULL,
    MONTANT_TOTAL DECIMAL(18,2) NULL,

    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 8. BONS D'ENTREE
CREATE TABLE SENTREE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    NUMERO VARCHAR(50) NOT NULL,
    DATE_ENTREE DATETIME NOT NULL DEFAULT GETDATE(),
    FOURNISSEUR_ID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES SFOURNISSEUR(ID),

    -- Statut
    STATUT VARCHAR(20) DEFAULT 'BROUILLON' CHECK (STATUT IN ('BROUILLON', 'VALIDE', 'ANNULE')),

    -- Montants
    TOTAL_HT DECIMAL(18,2) DEFAULT 0,
    TOTAL_TVA DECIMAL(18,2) DEFAULT 0,
    TOTAL_TTC DECIMAL(18,2) DEFAULT 0,

    -- Références
    REFERENCE VARCHAR(100),
    NOTES NVARCHAR(500),

    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    VALIDE_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    VALIDE_AT DATETIME NULL,
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 9. LIGNES DE BON D'ENTREE
CREATE TABLE MLENTREE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    BON_ENTREE_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SENTREE(ID),
    ARTICLE_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES MARTICLE(ID),

    QUANTITE DECIMAL(18,2) NOT NULL,
    PRIX_UNITAIRE_HT DECIMAL(18,2) NOT NULL,
    TVA_TX DECIMAL(5,2) DEFAULT 0,
    PRIX_UNITAIRE_TTC DECIMAL(18,2) NOT NULL,

    TOTAL_HT DECIMAL(18,2) NOT NULL,
    TOTAL_TVA DECIMAL(18,2) NOT NULL,
    TOTAL_TTC DECIMAL(18,2) NOT NULL,

    DATE_PEREMPTION DATE NULL,
    LOT_NUMERO VARCHAR(50) NULL,

    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 10. BONS DE SORTIE
CREATE TABLE SSORTIE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    NUMERO VARCHAR(50) NOT NULL,
    DATE_SORTIE DATETIME NOT NULL DEFAULT GETDATE(),
    DESTINATION VARCHAR(200),

    STATUT VARCHAR(20) DEFAULT 'BROUILLON' CHECK (STATUT IN ('BROUILLON', 'VALIDE', 'ANNULE')),

    NOM VARCHAR(200),
    FONCTION VARCHAR(50),
    NOTES NVARCHAR(500),

    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    VALIDE_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    VALIDE_AT DATETIME NULL,
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);

-- 11. LIGNES DE BON DE SORTIE
CREATE TABLE MLSORTIE (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    BON_SORTIE_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES SSORTIE(ID),
    ARTICLE_ID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES MARTICLE(ID),

    QUANTITE_D DECIMAL(18,2) NOT NULL,
    QUANTITE_R DECIMAL(18,2) NOT NULL,
    OBSERVATIONS NVARCHAR(500) NULL,

    CREATED_BY INT FOREIGN KEY REFERENCES USERS(IDUSER),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    UPDATED_BY INT NULL,
    DELETION_AT DATETIME NULL,
    DELETION_BY INT NULL
);
